#!/bin/bash
sync () {
	echo "user name?"
	read username
	svnsync synchronize https://d-cm.googlecode.com/svn --sync-username $username
}
status () {
	svn status
}
commit () {
	echo "Commit information?"
	read commit
	svn commit -m "$commit"
}
while getopts csS opt
do
    case "$opt" in
      c)  commit ;;
      S)  sync ;;
      s)  status ;;
      \?) echo >&2 \
	  "usage: $0 [-c] [-s] [-S]"
	  exit 1;;
    esac
done
echo "usage: $0 [-c] [-s] [-S]"
echo "-c: commit"
echo "-s: status"
echo "-S: synchronize"
shift `expr $OPTIND - 1`
